export const ActionTypes={
    MOVIES_LOADING:"MOVIES_LOADING",
    MOVİES_SUCCESS:"MOVİES_SUCCESS",
    MOVİES_ERROR:"MOVİES_ERROR",
    GENRES_LOADİNG:"GENRES_LOADİNG",
    GENRES_SUCCESS:"GENRES_SUCCESS",
    GENRES_ERROR:"GENRES_ERROR"
}